---
- name: Single task playbook to create a file using custom module
  hosts: localhost

  tasks:
    - name: Создание VM в Yandex Cloud
      yc_vm_instance:
        folder_id: "b1g22qi1cc8rq4avqgik"
        zone: "ru-central1-a"
        vm_name: "test-vm"
        core_count: 2
        memory_gb: 4
        image_id: "fd85i20p6h32jh7aic6h"
        disk_size_gb: 20
        ssh_key_path: "~/.ssh/id_ed25519.pub"
      register: result