---
- name: Single task playbook to create a file using custom module
  hosts: localhost

  tasks:
    - name: Создать текстовый файл с помощью пользовательского модуля
      yc_vm_instance:
        folder_id: "b1g22qi1cc8rq4avqgik"
        zone: "ru-central1-a"
        vm_name: "test-vm"
        core_count: 2
        memory_gb: 4
        image_family: "ubuntu-2004-lts"
        disk_size_gb: 20
        ssh_key_path: "/home/dio/.ssh/id_ed25519.pub"
      register: result